import '/src/component/hero/Hero.css';

export default function Hero () {
    return (
        <section className="Hero">

          <div className='HeroContent'>
              <h4>We Have Everything  <br /> Your <span id="car" >Car</span>  Need </h4>
              <p>Who want to buy used, Certified and new cars, This is the best 
                place for them, <br /> There are many types of cars in our store, new, old, come to our store and find your dream car.
              </p>

              <button id='Discoverbtn'>
                Discover Today
              </button>
          </div>


                        <section className='BrandSelection'>

                        <select>
<option value="Model/Brand">Model/Brand</option>
<option value="AAQN" >AAQN</option>
<option value="ACA" >ACA</option>
<option value="ACURA" >ACURA</option>
<option value="ADLY" >ADLY</option>
<option value="ADVENTURE" >ADVENTURE</option>
<option value="AIRS" >AIRS</option>
<option value="AIRSTREAM" >AIRSTREAM</option>
<option value="ALCOM" >ALCOM</option>
<option value="ALFA ROMEO" >ALFA ROMEO</option>
<option value="ALINER" >ALINER</option>
<option value="ALLI" >ALLI</option>
<option value="ALOHA" >ALOHA</option>
<option value="ALUM" >ALUM</option>
<option value="AMERI-CAMP" >AMERI-CAMP</option>
<option value="AMERICAN" >AMERICAN</option>
<option value="AMERICAN MOTORS" >AMERICAN MOTORS</option>
<option value="AMIG" >AMIG</option>
<option value="ANDERSON" >ANDERSON</option>
<option value="ANDERSON MFG" >ANDERSON MFG</option>
<option value="ANVI" >ANVI</option>
<option value="ANVL" >ANVL</option>
<option value="AOUB" >AOUB</option>
<option value="APRILIA" >APRILIA</option>
<option value="ARCT" >ARCT</option>
<option value="ARCTIC CAT" >ARCTIC CAT</option>
<option value="ARGO" >ARGO</option>
<option value="ARIS" >ARIS</option>
<option value="ASPN" >ASPN</option>
<option value="ASSEMBLED" >ASSEMBLED</option>
<option value="ASTON MARTIN" >ASTON MARTIN</option>
<option value="ASTR" >ASTR</option>
<option value="ATOKA" >ATOKA</option>
<option value="AUDI">AUDI</option>
<option value="AUOX" >AUOX</option>
<option value="AUSTIN" >AUSTIN</option>
<option value="AUTOCAR LLC" >AUTOCAR LLC</option>
<option value="AUTU" >AUTU</option>
<option value="AVEN" >AVEN</option>
<option value="AXPS" >AXPS</option>
<option value="BAJAJ" >BAJAJ</option>
<option value="BANE" >BANE</option>
<option value="BASHAN" >BASHAN</option>
<option value="BASS" >BASS</option>
<option value="BAYL" >BAYL</option>
<option value="BAYLINER" >BAYLINER</option>
<option value="BEAL" >BEAL</option>
<option value="BEBU" >BEBU</option>
<option value="BELMONT" >BELMONT</option>
<option value="BENN" >BENN</option>
<option value="BENTLEY" >BENTLEY</option>
<option value="BERTONE" >BERTONE</option>
<option value="BHNC" >BHNC</option>
<option value="BIG DOG" >BIG DOG</option>
<option value="BIG TEX TRAILER CO INC" >BIG TEX TRAILER CO INC</option>
<option value="BIGT" >BIGT</option>
<option value="BISO" >BISO</option>
<option value="BKIG" >BKIG</option>
<option value="BLAZ" >BLAZ</option>
<option value="BLUE BIRD" >BLUE BIRD</option>
<option value="BLUE WAVE" >BLUE WAVE</option>
<option value="BMBR" >BMBR</option>
<option value="BMW" >BMW</option>
<option value="BOAT" >BOAT</option>
<option value="BOWM" >BOWM</option>
<option value="BRAVO" >BRAVO</option>
<option value="BREC" >BREC</option>
<option value="BRECKENRIDGE" >BRECKENRIDGE</option>
<option value="BREN" >BREN</option>
<option value="BRENDERUP" >BRENDERUP</option>
<option value="BRI-MAR MANUFACTURING" >BRI-MAR MANUFACTURING</option>
<option value="BROO" >BROO</option>
<option value="BRYA" >BRYA</option>
<option value="BUELL" >BUELL</option>
<option value="BUICK">BUICK</option>
<option value="BULL" >BULL</option>
<option value="BUTLER" >BUTLER</option>
<option value="BXBO" >BXBO</option>
<option value="BYER" >BYER</option>
<option value="CADILLAC" >CADILLAC</option>
<option value="CALT" >CALT</option>
<option value="CAMEO BY CARRIAGE" >CAMEO BY CARRIAGE</option>
<option value="CAMP" >CAMP</option>
<option value="CAMPER" >CAMPER</option>
<option value="CAN" >CAN</option>
<option value="CAN-AM" >CAN-AM</option>
<option value="CAPITAL" >CAPITAL</option>
<option value="CARA" >CARA</option>
<option value="CARD" >CARD</option>
<option value="CARGO" >CARGO</option>
<option value="CARR" >CARR</option>
<option value="CARRIAGE" >CARRIAGE</option>
<option value="CARRY ON" >CARRY ON</option>
<option value="CARS" >CARS</option>
<option value="CARSON" >CARSON</option>
<option value="CCHM" >CCHM</option>
<option value="CDPT" >CDPT</option>
<option value="CEDA" >CEDA</option>
<option value="CEDAR CREEK" >CEDAR CREEK</option>
<option value="CF MOTO" >CF MOTO</option>
<option value="CFMO" >CFMO</option>
<option value="CHAP" >CHAP</option>
<option value="CHAPARRAL" >CHAPARRAL</option>
<option value="CHAPPAREL" >CHAPPAREL</option>
<option value="CHECKER" >CHECKER</option>
<option value="CHER" >CHER</option>
<option value="CHEROKEE" >CHEROKEE</option>
<option value="CHEVROLET" >CHEVROLET</option>
<option value="CHRYSLER" >CHRYSLER</option>
<option value="CIHF" >CIHF</option>
<option value="CIMC" >CIMC</option>
<option value="CIRC" >CIRC</option>
<option value="CITH" >CITH</option>
<option value="CITR" >CITR</option>
<option value="CLASSIC ROADSTER" >CLASSIC ROADSTER</option>
<option value="CMMS" >CMMS</option>
<option value="COACH" >COACH</option>
<option value="COACHMEN" >COACHMEN</option>
<option value="COBA" >COBA</option>
<option value="COBRA" >COBRA</option>
<option value="COBRA TRIKE" >COBRA TRIKE</option>
<option value="COFF" >COFF</option>
<option value="COLE" >COLE</option>
<option value="COLEMAN" >COLEMAN</option>
<option value="COLU" >COLU</option>
<option value="COLUMBIA" >COLUMBIA</option>
<option value="COMM" >COMM</option>
<option value="CONT" >CONT</option>
<option value="COTTRELL" >COTTRELL</option>
<option value="COTTRELL INC" >COTTRELL INC</option>
<option value="CRES" >CRES</option>
<option value="CRESTLINER" >CRESTLINER</option>
<option value="CROS" >CROS</option>
<option value="CROSSROADS" >CROSSROADS</option>
<option value="CROWNLINE" >CROWNLINE</option>
<option value="CRRV" >CRRV</option>
<option value="CRUI" >CRUI</option>
<option value="CRUISER" >CRUISER</option>
<option value="CURR" >CURR</option>
<option value="CUST TANKER" >CUST TANKER</option>
<option value="CWLN" >CWLN</option>
<option value="DAMO" >DAMO</option>
<option value="DATSUN" >DATSUN</option>
<option value="DAVI" >DAVI</option>
<option value="DESOTO" >DESOTO</option>
<option value="DHM" >DHM</option>
<option value="DIAHATSU" >DIAHATSU</option>
<option value="DIAM" >DIAM</option>
<option value="DIAMOND" >DIAMOND</option>
<option value="DIAMOND REO" >DIAMOND REO</option>
<option value="DMVZ" >DMVZ</option>
<option value="DODGE" >DODGE</option>
<option value="DOLH" >DOLH</option>
<option value="DOLP" >DOLP</option>
<option value="DOOL" >DOOL</option>
<option value="DOOLITTLE" >DOOLITTLE</option>
<option value="DOON" >DOON</option>
<option value="DORSEY" >DORSEY</option>
<option value="DRV" >DRV</option>
<option value="DSON" >DSON</option>
<option value="DUCATI" >DUCATI</option>
<option value="DUTC" >DUTC</option>
<option value="DUTCHMAN" >DUTCHMAN</option>
<option value="DUTCHMEN" >DUTCHMEN</option>
<option value="EAGL" >EAGL</option>
<option value="EAGLE" >EAGLE</option>
<option value="EAST" >EAST</option>
<option value="ECHO" >ECHO</option>
<option value="ECLIPSE" >ECLIPSE</option>
<option value="ELIT" >ELIT</option>
<option value="ELKG" >ELKG</option>
<option value="ELYX" >ELYX</option>
<option value="ENCL" >ENCL</option>
<option value="ESBF" >ESBF</option>
<option value="ETW" >ETW</option>
<option value="EVER" >EVER</option>
<option value="EXCALIBUR" >EXCALIBUR</option>
<option value="EXEL" >EXEL</option>
<option value="EYBK" >EYBK</option>
<option value="EZ" >EZ</option>
<option value="EZHA" >EZHA</option>
<option value="FABR" >FABR</option>
<option value="FAHD" >FAHD</option>
<option value="FCUH" >FCUH</option>
<option value="FEATHERLITE MFG INC" >FEATHERLITE MFG INC</option>
<option value="FERRARI" >FERRARI</option>
<option value="FIAT" >FIAT</option>
<option value="FIRE" >FIRE</option>
<option value="FISKER" >FISKER</option>
<option value="FISKER AUTOMOTIVE" >FISKER AUTOMOTIVE</option>
<option value="FLAG" >FLAG</option>
<option value="FLAGSTAFF" >FLAGSTAFF</option>
<option value="FLEE" >FLEE</option>
<option value="FLEETWOOD" >FLEETWOOD</option>
<option value="FONTAINE" >FONTAINE</option>
<option value="FOR" >FOR</option>
<option value="FORD" >FORD</option>
<option value="FORE TRAVEL U295" >FORE TRAVEL U295</option>
<option value="FOREST RIVER" >FOREST RIVER</option>
<option value="FORR" >FORR</option>
<option value="FORS" >FORS</option>
<option value="FOST" >FOST</option>
<option value="FOSTER" >FOSTER</option>
<option value="FOUR" >FOUR</option>
<option value="FOX" >FOX</option>
<option value="FRE" >FRE</option>
<option value="FREEDOM" >FREEDOM</option>
<option value="FREIGHTLINER" >FREIGHTLINER</option>
<option value="FRRV" >FRRV</option>
<option value="FRUEHAUF" >FRUEHAUF</option>
<option value="FTWD" >FTWD</option>
<option value="FVFE" >FVFE</option>
<option value="FVFG" >FVFG</option>
<option value="FVOR" >FVOR</option>
<option value="FWIC" >FWIC</option>
<option value="GAMB" >GAMB</option>
<option value="GATO" >GATO</option>
<option value="GATR" >GATR</option>
<option value="GDAN" >GDAN</option>
<option value="GDRF" >GDRF</option>
<option value="GDRV" >GDRV</option>
<option value="GEEL" >GEEL</option>
<option value="GEM" >GEM</option>
<option value="GENE" >GENE</option>
<option value="GENERAL MOTORS" >GENERAL MOTORS</option>
<option value="GENESIS" >GENESIS</option>
<option value="GENUINE SCOOTER CO." >GENUINE SCOOTER CO.</option>
<option value="GEO" >GEO</option>
<option value="GEOR" >GEOR</option>
<option value="GGSD" >GGSD</option>
<option value="GJDB" >GJDB</option>
<option value="GLOBAL ELECTRIC MOTORS" >GLOBAL ELECTRIC MOTORS</option>
<option value="GMC" >GMC</option>
<option value="GODFREY" >GODFREY</option>
<option value="GOOS" >GOOS</option>
<option value="GOOSENECK TRAILERS" >GOOSENECK TRAILERS</option>
<option value="GPLB" >GPLB</option>
<option value="GRAD" >GRAD</option>
<option value="GRADY WHITE" >GRADY WHITE</option>
<option value="GRAI" >GRAI</option>
<option value="GRAN" >GRAN</option>
<option value="GRAND DESIGN" >GRAND DESIGN</option>
<option value="GRDE" >GRDE</option>
<option value="GREA" >GREA</option>
<option value="GREAT DANE" >GREAT DANE</option>
<option value="GREAT DANE TRAILER" >GREAT DANE TRAILER</option>
<option value="GREGOR" >GREGOR</option>
<option value="GRT" >GRT</option>
<option value="GRUPO REMOLQUES DEL NORTE" >GRUPO REMOLQUES DEL NORTE</option>
<option value="GSUP" >GSUP</option>
<option value="GULF STREAM" >GULF STREAM</option>
<option value="GULFSTREAM" >GULFSTREAM</option>
<option value="H&amp;H" >H&amp;H</option>
<option value="H_AND_H" >H_AND_H</option>
<option value="HARLEY-DAVIDSON" >HARLEY-DAVIDSON</option>
<option value="HAUL" >HAUL</option>
<option value="HAUL MARK IND" >HAUL MARK IND</option>
<option value="HAWK" >HAWK</option>
<option value="HCXR" >HCXR</option>
<option value="HEART LAND" >HEART LAND</option>
<option value="HEART MANUFACTURING" >HEART MANUFACTURING</option>
<option value="HEARTLAND" >HEARTLAND</option>
<option value="HEARTLAND RV" >HEARTLAND RV</option>
<option value="HEARTLAND RVS" >HEARTLAND RVS</option>
<option value="HEARTLAND RV-S" >HEARTLAND RV-S</option>
<option value="HEIL" >HEIL</option>
<option value="HH" >HH</option>
<option value="HIGH" >HIGH</option>
<option value="HIGH VIEW MANUFACTURING" >HIGH VIEW MANUFACTURING</option>
<option value="HIGHLAND RIDGE" >HIGHLAND RIDGE</option>
<option value="HILO" >HILO</option>
<option value="HINO" >HINO</option>
<option value="HITC" >HITC</option>
<option value="HMDE" >HMDE</option>
<option value="HOLI" >HOLI</option>
<option value="HOLM" >HOLM</option>
<option value="HOLR" >HOLR</option>
<option value="HOME" >HOME</option>
<option value="HOMEMADE" >HOMEMADE</option>
<option value="HONDA" >HONDA</option>
<option value="HOOP" >HOOP</option>
<option value="HORN" >HORN</option>
<option value="HORSE" >HORSE</option>
<option value="HORTON" >HORTON</option>
<option value="HRLD" >HRLD</option>
<option value="HRTL" >HRTL</option>
<option value="HUDSON BROS TRAILER MFG" >HUDSON BROS TRAILER MFG</option>
<option value="HUMMER" >HUMMER</option>
<option value="HUNT" >HUNT</option>
<option value="HURR" >HURR</option>
<option value="HURRICANE" >HURRICANE</option>
<option value="HUSQVARNA" >HUSQVARNA</option>
<option value="HYDS" >HYDS</option>
<option value="HYOSUNG" >HYOSUNG</option>
<option value="HYTR" >HYTR</option>
<option value="HYUNDAI" >HYUNDAI</option>
<option value="HYUNDAI TRANSLEAD INC" >HYUNDAI TRANSLEAD INC</option>
<option value="IC CORPORATION" >IC CORPORATION</option>
<option value="IMAG" >IMAG</option>
<option value="INDIAN" >INDIAN</option>
<option value="INFINITI" >INFINITI</option>
<option value="INMAN" >INMAN</option>
<option value="INTE" >INTE</option>
<option value="INTERNATIONAL" >INTERNATIONAL</option>
<option value="INTS" >INTS</option>
<option value="ISUZU" >ISUZU</option>
<option value="ITAS" >ITAS</option>
<option value="JAGUAR" >JAGUAR</option>
<option value="JAMA" >JAMA</option>
<option value="JAY" >JAY</option>
<option value="JAY FLIGHT" >JAY FLIGHT</option>
<option value="JAYC" >JAYC</option>
<option value="JAYCO" >JAYCO</option>
<option value="JAYCO JAY FLIGHT" >JAYCO JAY FLIGHT</option>
<option value="JAYCO JAYFLIGHT" >JAYCO JAYFLIGHT</option>
<option value="JAYF" >JAYF</option>
<option value="JEEP" >JEEP</option>
<option value="JIAJUE" >JIAJUE</option>
<option value="JIAN" >JIAN</option>
<option value="JOHN DEERE" >JOHN DEERE</option>
<option value="KALY" >KALY</option>
<option value="KAUFMAN" >KAUFMAN</option>
<option value="KAUFMAN TRAILERS" >KAUFMAN TRAILERS</option>
<option value="KAWASAKI">KAWASAKI</option>
<option value="KAYO" >KAYO</option>
<option value="KBH" >KBH</option>
<option value="KENT" >KENT</option>
<option value="KENTUCKY MFG" >KENTUCKY MFG</option>
<option value="KENWORTH" >KENWORTH</option>
<option value="KEY" >KEY</option>
<option value="KEYSTONE" >KEYSTONE</option>
<option value="KEYSTONE RV" >KEYSTONE RV</option>
<option value="KIA" >KIA</option>
<option value="KIEFER BUILT INC" >KIEFER BUILT INC</option>
<option value="KIT" >KIT</option>
<option value="KODI" >KODI</option>
<option value="KOM" >KOM</option>
<option value="KOMF" >KOMF</option>
<option value="KQFP" >KQFP</option>
<option value="KTM" >KTM</option>
<option value="KUOG" >KUOG</option>
<option value="KUTB" >KUTB</option>
<option value="KYHI" >KYHI</option>
<option value="KYMCO USA INC" >KYMCO USA INC</option>
<option value="KYST" >KYST</option>
<option value="KZ" >KZ</option>
<option value="KZDV" >KZDV</option>
<option value="KZRV" >KZRV</option>
<option value="KZSP" >KZSP</option>
<option value="LAMAR" >LAMAR</option>
<option value="LAMBORGHINI" >LAMBORGHINI</option>
<option value="LANCIA" >LANCIA</option>
<option value="LAND ROVER" >LAND ROVER</option>
<option value="LANDOLL CORP" >LANDOLL CORP</option>
<option value="LARS" >LARS</option>
<option value="LAYT" >LAYT</option>
<option value="LAYTON" >LAYTON</option>
<option value="LBT" >LBT</option>
<option value="LBT INC" >LBT INC</option>
<option value="LDBQ" >LDBQ</option>
<option value="LEBE" >LEBE</option>
<option value="LEXUS" >LEXUS</option>
<option value="LGS INDUSTRIES" >LGS INDUSTRIES</option>
<option value="LIBE" >LIBE</option>
<option value="LIEF" >LIEF</option>
<option value="LIFAN" >LIFAN</option>
<option value="LIKF" >LIKF</option>
<option value="LINCOLN" >LINCOLN</option>
<option value="LOAD" >LOAD</option>
<option value="LOGA" >LOGA</option>
<option value="LOOK" >LOOK</option>
<option value="LOTUS" >LOTUS</option>
<option value="LOWE" >LOWE</option>
<option value="LRSO" >LRSO</option>
<option value="LUBBOCK" >LUBBOCK</option>
<option value="LUCID" >LUCID</option>
<option value="LUCID MOTORS" >LUCID MOTORS</option>
<option value="LUFK" >LUFK</option>
<option value="MACH" >MACH</option>
<option value="MACK" >MACK</option>
<option value="MACT" >MACT</option>
<option value="MAGNUM" >MAGNUM</option>
<option value="MALL" >MALL</option>
<option value="MALLARD" >MALLARD</option>
<option value="MANA" >MANA</option>
<option value="MANAC INC" >MANAC INC</option>
<option value="MANL" >MANL</option>
<option value="MARIAH" >MARIAH</option>
<option value="MARINE" >MARINE</option>
<option value="MARN" >MARN</option>
<option value="MASERATI" >MASERATI</option>
<option value="MATE" >MATE</option>
<option value="MAXU" >MAXU</option>
<option value="MAXUM" >MAXUM</option>
<option value="MAZDA" >MAZDA</option>
<option value="MCLAREN" >MCLAREN</option>
<option value="MCLAREN AUTOMOTIVE" >MCLAREN AUTOMOTIVE</option>
<option value="MERCEDES-BENZ" >MERCEDES-BENZ</option>
<option value="MERCURY" >MERCURY</option>
<option value="MESA" >MESA</option>
<option value="MG" >MG</option>
<option value="MIDWEST" >MIDWEST</option>
<option value="MINI" >MINI</option>
<option value="MISS" >MISS</option>
<option value="MITSUBISHI" >MITSUBISHI</option>
<option value="MITSUBISHI FUSO" >MITSUBISHI FUSO</option>
<option value="MITSUBISHI FUSO TRUCK" >MITSUBISHI FUSO TRUCK</option>
<option value="MITSUBISHI FUSO TRUCK OF" >MITSUBISHI FUSO TRUCK OF</option>
<option value="MONA" >MONA</option>
<option value="MONON 45X96" >MONON 45X96</option>
<option value="MONR" >MONR</option>
<option value="MONT" >MONT</option>
<option value="MONTEGO" >MONTEGO</option>
<option value="MORR" >MORR</option>
<option value="MOTORCYCLE" >MOTORCYCLE</option>
<option value="MOUN" >MOUN</option>
<option value="MUS" >MUS</option>
<option value="MV AGUSTA" >MV AGUSTA</option>
<option value="MYGR" >MYGR</option>
<option value="NASH" >NASH</option>
<option value="NEWMAR" >NEWMAR</option>
<option value="NEWR" >NEWR</option>
<option value="NISSAN">NISSAN</option>
<option value="NITR" >NITR</option>
<option value="NLRS" >NLRS</option>
<option value="NNT" >NNT</option>
<option value="NOMA" >NOMA</option>
<option value="NORS" >NORS</option>
<option value="NORT" >NORT</option>
<option value="NORTHLAND" >NORTHLAND</option>
<option value="NU WA" >NU WA</option>
<option value="NUWA" >NUWA</option>
<option value="NVAE" >NVAE</option>
<option value="O DAY" >O DAY</option>
<option value="OLDSMOBILE" >OLDSMOBILE</option>
<option value="OPEN" >OPEN</option>
<option value="OPEN RANGE" >OPEN RANGE</option>
<option value="OPRG" >OPRG</option>
<option value="ORVM" >ORVM</option>
<option value="OTHER" >OTHER</option>
<option value="OTHI" >OTHI</option>
<option value="OTHR" >OTHR</option>
<option value="OUTB" >OUTB</option>
<option value="P&amp;T" >P&amp;T</option>
<option value="PACA" >PACA</option>
<option value="PACC" >PACC</option>
<option value="PACE" >PACE</option>
<option value="PACE AMERICAN" >PACE AMERICAN</option>
<option value="PACKARD" >PACKARD</option>
<option value="PALA" >PALA</option>
<option value="PALO" >PALO</option>
<option value="PALOMINO" >PALOMINO</option>
<option value="PARK" >PARK</option>
<option value="PASSPORT" >PASSPORT</option>
<option value="PBAS" >PBAS</option>
<option value="PEAC" >PEAC</option>
<option value="PETERBILT" >PETERBILT</option>
<option value="PHOE" >PHOE</option>
<option value="PHOENIX" >PHOENIX</option>
<option value="PIAGGIO" >PIAGGIO</option>
<option value="PIERCE MFG. INC." >PIERCE MFG. INC.</option>
<option value="PIJQ" >PIJQ</option>
<option value="PILG" >PILG</option>
<option value="PINES" >PINES</option>
<option value="PJ" >PJ</option>
<option value="PJ TRAILERS" >PJ TRAILERS</option>
<option value="PJTM" >PJTM</option>
<option value="PJVS" >PJVS</option>
<option value="PLYMOUTH" >PLYMOUTH</option>
<option value="PMEV" >PMEV</option>
<option value="PNTW" >PNTW</option>
<option value="POLA" >POLA</option>
<option value="POLARIS">POLARIS</option>
<option value="POLESTAR" >POLESTAR</option>
<option value="PONTIAC" >PONTIAC</option>
<option value="PORSCHE" >PORSCHE</option>
<option value="PORT CITY TRAILERS," >PORT CITY TRAILERS,</option>
<option value="PREMIER" >PREMIER</option>
<option value="PREVOST" >PREVOST</option>
<option value="PROL" >PROL</option>
<option value="PROW" >PROW</option>
<option value="PROWLER" >PROWLER</option>
<option value="PUMA" >PUMA</option>
<option value="QIPA" >QIPA</option>
<option value="QUAL" >QUAL</option>
<option value="QUALITY" >QUALITY</option>
<option value="R&amp;M" >R&amp;M</option>
<option value="RAM" >RAM</option>
<option value="RANC" >RANC</option>
<option value="RANGER" >RANGER</option>
<option value="RAUF" >RAUF</option>
<option value="RAVENS METAL PRODUCTS INC" >RAVENS METAL PRODUCTS INC</option>
<option value="RAWM" >RAWM</option>
<option value="RC" >RC</option>
<option value="RCKW" >RCKW</option>
<option value="RDCA" >RDCA</option>
<option value="REC" >REC</option>
<option value="RECREATION BY DESIGN" >RECREATION BY DESIGN</option>
<option value="RECREATIONAL" >RECREATIONAL</option>
<option value="REDR" >REDR</option>
<option value="REGA" >REGA</option>
<option value="REIT" >REIT</option>
<option value="RELIANCE TRAILER MFG" >RELIANCE TRAILER MFG</option>
<option value="RETCO" >RETCO</option>
<option value="RINK" >RINK</option>
<option value="RINKER" >RINKER</option>
<option value="RIVERSIDE RV" >RIVERSIDE RV</option>
<option value="RIVIAN" >RIVIAN</option>
<option value="RIVIERA CRUISER" >RIVIERA CRUISER</option>
<option value="RIYA" >RIYA</option>
<option value="ROAD" >ROAD</option>
<option value="ROAD WARRI 427" >ROAD WARRI 427</option>
<option value="ROADMASTER" >ROADMASTER</option>
<option value="ROADMASTER RAIL" >ROADMASTER RAIL</option>
<option value="ROAF" >ROAF</option>
<option value="ROAM" >ROAM</option>
<option value="ROBALO" >ROBALO</option>
<option value="ROCK" >ROCK</option>
<option value="ROCKWOOD" >ROCKWOOD</option>
<option value="ROCKWOOD BY FOREST R" >ROCKWOOD BY FOREST R</option>
<option value="ROLLS-ROYCE" >ROLLS-ROYCE</option>
<option value="ROYAL ENFIELD MOTORS" >ROYAL ENFIELD MOTORS</option>
<option value="RPS" >RPS</option>
<option value="RSI" >RSI</option>
<option value="RSSI" >RSSI</option>
<option value="RVIS" >RVIS</option>
<option value="SAAB">SAAB</option>
<option value="SALEEN" >SALEEN</option>
<option value="SALEM" >SALEM</option>
<option value="SALM" >SALM</option>
<option value="SALV" >SALV</option>
<option value="SAND" >SAND</option>
<option value="SANDSPORT" >SANDSPORT</option>
<option value="SANM" >SANM</option>
<option value="SANYANG" >SANYANG</option>
<option value="SATP" >SATP</option>
<option value="SATURN" >SATURN</option>
<option value="SCAMP" >SCAMP</option>
<option value="SCION" >SCION</option>
<option value="SCOT" >SCOT</option>
<option value="SCRA" >SCRA</option>
<option value="SDCS" >SDCS</option>
<option value="SDWP" >SDWP</option>
<option value="SEA" >SEA</option>
<option value="SEA ARK" >SEA ARK</option>
<option value="SEA DOO" >SEA DOO</option>
<option value="SEA FOX" >SEA FOX</option>
<option value="SEA RAY" >SEA RAY</option>
<option value="SEAD" >SEAD</option>
<option value="SEADOO" >SEADOO</option>
<option value="SEAGRAVE FIRE APPARATUS" >SEAGRAVE FIRE APPARATUS</option>
<option value="SEAO" >SEAO</option>
<option value="SEAP" >SEAP</option>
<option value="SEGW" >SEGW</option>
<option value="SEKQ" >SEKQ</option>
<option value="SER" >SER</option>
<option value="SGOH" >SGOH</option>
<option value="SHAD" >SHAD</option>
<option value="SHAS" >SHAS</option>
<option value="SHASTA" >SHASTA</option>
<option value="SHORE LANDER" >SHORE LANDER</option>
<option value="SIER" >SIER</option>
<option value="SKEETER" >SKEETER</option>
<option value="SKI DOO" >SKI DOO</option>
<option value="SKI-DOO" >SKI-DOO</option>
<option value="SKYLINE" >SKYLINE</option>
<option value="SLKY" >SLKY</option>
<option value="SLTO" >SLTO</option>
<option value="SMART" >SMART</option>
<option value="SNFE" >SNFE</option>
<option value="SOLID" >SOLID</option>
<option value="SONI" >SONI</option>
<option value="SOON" >SOON</option>
<option value="SOUT" >SOUT</option>
<option value="SOUTHBAY" >SOUTHBAY</option>
<option value="SPARTAN" >SPARTAN</option>
<option value="SPARTAN MOTORS" >SPARTAN MOTORS</option>
<option value="SPORT TREK" >SPORT TREK</option>
<option value="SPORTSMASTER SERIES" >SPORTSMASTER SERIES</option>
<option value="SPPR" >SPPR</option>
<option value="SPRI" >SPRI</option>
<option value="SPRINTER" >SPRINTER</option>
<option value="SPRT" >SPRT</option>
<option value="SSTR" >SSTR</option>
<option value="SSVA" >SSVA</option>
<option value="STARCRAFT" >STARCRAFT</option>
<option value="STCF" >STCF</option>
<option value="STEA" >STEA</option>
<option value="STEH" >STEH</option>
<option value="STERLING" >STERLING</option>
<option value="STLO" >STLO</option>
<option value="STOU" >STOU</option>
<option value="STOUGHTON TRAILERS INC" >STOUGHTON TRAILERS INC</option>
<option value="STRI" >STRI</option>
<option value="STRICK TRAILERS" >STRICK TRAILERS</option>
<option value="STUDEBAKER" >STUDEBAKER</option>
<option value="SUBARU" >SUBARU</option>
<option value="SUN CHASER" >SUN CHASER</option>
<option value="SUN COUNTRY" >SUN COUNTRY</option>
<option value="SUNB" >SUNB</option>
<option value="SUND" >SUND</option>
<option value="SUNL" >SUNL</option>
<option value="SUNNYBROOK" >SUNNYBROOK</option>
<option value="SUNR" >SUNR</option>
<option value="SURE" >SURE</option>
<option value="SURV" >SURV</option>
<option value="SUZU" >SUZU</option>
<option value="SUZUKI" >SUZUKI</option>
<option value="SWEE" >SWEE</option>
<option value="TAHOE" >TAHOE</option>
<option value="TAIZ" >TAIZ</option>
<option value="TALBERT" >TALBERT</option>
<option value="TANK" >TANK</option>
<option value="TAO TAO" >TAO TAO</option>
<option value="TBUS" >TBUS</option>
<option value="TEEN" >TEEN</option>
<option value="TERRYS" >TERRYS</option>
<option value="TESLA">TESLA</option>
<option value="TEX" >TEX</option>
<option value="THMC" >THMC</option>
<option value="THOMAS" >THOMAS</option>
<option value="THOR" >THOR</option>
<option value="TIAU" >TIAU</option>
<option value="TIFFIN MOTORHOMES INC" >TIFFIN MOTORHOMES INC</option>
<option value="TIGE" >TIGE</option>
<option value="TIMB" >TIMB</option>
<option value="TIMP" >TIMP</option>
<option value="TIMT" >TIMT</option>
<option value="TIOG" >TIOG</option>
<option value="TITA" >TITA</option>
<option value="TOPH" >TOPH</option>
<option value="TOWR" >TOWR</option>
<option value="TOYOTA" >TOYOTA</option>
<option value="TPEW" >TPEW</option>
<option value="TQIM" >TQIM</option>
<option value="TRA" >TRA</option>
<option value="TRAC" >TRAC</option>
<option value="TRACKER" >TRACKER</option>
<option value="TRAIL KING" >TRAIL KING</option>
<option value="TRAILER" >TRAILER</option>
<option value="TRAILMOBILE" >TRAILMOBILE</option>
<option value="TRAILS WEST" >TRAILS WEST</option>
<option value="TRAL" >TRAL</option>
<option value="TRAV" >TRAV</option>
<option value="TRAVEL LITE" >TRAVEL LITE</option>
<option value="TRICK" >TRICK</option>
<option value="TRIT" >TRIT</option>
<option value="TRIUMPH" >TRIUMPH</option>
<option value="TRIUMPH CAR" >TRIUMPH CAR</option>
<option value="TRLK" >TRLK</option>
<option value="TRLR" >TRLR</option>
<option value="TRMC" >TRMC</option>
<option value="TRS" >TRS</option>
<option value="TSEF" >TSEF</option>
<option value="TTHM" >TTHM</option>
<option value="TUFF" >TUFF</option>
<option value="TVR" >TVR</option>
<option value="TWIL" >TWIL</option>
<option value="TWIS" >TWIS</option>
<option value="UHZN" >UHZN</option>
<option value="UNITED CARGO TRAILER" >UNITED CARGO TRAILER</option>
<option value="UNITED EXPRESS LINE INC" >UNITED EXPRESS LINE INC</option>
<option value="UNKN" >UNKN</option>
<option value="UPLO" >UPLO</option>
<option value="URAL" >URAL</option>
<option value="URWI" >URWI</option>
<option value="UTC" >UTC</option>
<option value="UTI" >UTI</option>
<option value="UTILITY" >UTILITY</option>
<option value="UTILITY TRAILER MFG" >UTILITY TRAILER MFG</option>
<option value="VANCO TRAILER" >VANCO TRAILER</option>
<option value="VANDERHALL" >VANDERHALL</option>
<option value="VANG" >VANG</option>
<option value="VANGUARD NATIONAL TRAILER" >VANGUARD NATIONAL TRAILER</option>
<option value="VANR" >VANR</option>
<option value="VENTURE" >VENTURE</option>
<option value="VESPA" >VESPA</option>
<option value="VIBE" >VIBE</option>
<option value="VICTORY" >VICTORY</option>
<option value="VINT" >VINT</option>
<option value="VNTC" >VNTC</option>
<option value="VOLKSWAGEN" >VOLKSWAGEN</option>
<option value="VOLT" >VOLT</option>
<option value="VOLVO">VOLVO</option>
<option value="VYVC" >VYVC</option>
<option value="WABASH" >WABASH</option>
<option value="WABASH NATIONAL CORP" >WABASH NATIONAL CORP</option>
<option value="WALK" >WALK</option>
<option value="WANC" >WANC</option>
<option value="WBTV" >WBTV</option>
<option value="WEBBCRAFT" >WEBBCRAFT</option>
<option value="WELLS CARGO" >WELLS CARGO</option>
<option value="WELS" >WELS</option>
<option value="WESTERN STAR" >WESTERN STAR</option>
<option value="WESTERN STAR/AUTO CAR" >WESTERN STAR/AUTO CAR</option>
<option value="WFAL" >WFAL</option>
<option value="WIL" >WIL</option>
<option value="WILD" >WILD</option>
<option value="WILDERNESS BY FLEETW" >WILDERNESS BY FLEETW</option>
<option value="WILDWOOD" >WILDWOOD</option>
<option value="WILLY" >WILLY</option>
<option value="WILSON" >WILSON</option>
<option value="WILSON TRAILER CO" >WILSON TRAILER CO</option>
<option value="WINNEBAGO" >WINNEBAGO</option>
<option value="WLDE" >WLDE</option>
<option value="WOLF" >WOLF</option>
<option value="WORKHORSE" >WORKHORSE</option>
<option value="WORKHORSE CUSTOM CHASSIS" >WORKHORSE CUSTOM CHASSIS</option>
<option value="WORLEY" >WORLEY</option>
<option value="XNA" >XNA</option>
<option value="YACH" >YACH</option>
<option value="YAMAHA">YAMAHA</option>
<option value="YIBEN" >YIBEN</option>
<option value="YMCL" >YMCL</option>
<option value="YNGF" >YNGF</option>
<option value="YONG" >YONG</option>
<option value="ZERO MOTORCYCLES INC" >ZERO MOTORCYCLES INC</option>
<option value="ZHEJ" >ZHEJ</option>
<option value="ZIEMAN" >ZIEMAN</option>
</select>

<br />
                <select id="Condition">
                    <option value="Condition">Condition</option>
                    <option value="saab">Brand new</option>
                    <option value="opel">Fairly used</option>
                    <option value="audi">Swap</option>
               </select>


                <select id="Year">
                    <option value="Year">Year</option>
                    <option value="2000">2000</option>
                    <option value="2001">2001</option>
                    <option value="2002">2002</option>
                    <option value="2003">2003</option>
                    <option value="2004">2004</option>
                    <option value="2005">2005</option>
                    <option value="2006">2006</option>
                    <option value="2007">2007</option>
                    <option value="2008">2008</option>
                    <option value="2009">2009</option>
                    <option value="2010">2010</option>
                    <option value="2011">2011</option>
                    <option value="2012">2012</option>
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
               </select>

                          <button className='FindBtn'>
                              Find Car
                          </button>



                        </section> 



        </section>
    )
}